from app.prompts.templates import (
    RISK_CLASSIFIER_PROMPT,
    WORKOUT_GENERATION_PROMPT,
    MEAL_PLAN_GENERATION_PROMPT,
    COACH_PROMPT,
    WORKOUT_ADAPTATION_PROMPT,
    EXERCISE_SUBSTITUTION_PROMPT,
    MEAL_ESTIMATION_PROMPT,
    PROGRESS_SUMMARY_PROMPT,
)

__all__ = [
    "RISK_CLASSIFIER_PROMPT",
    "WORKOUT_GENERATION_PROMPT",
    "MEAL_PLAN_GENERATION_PROMPT",
    "COACH_PROMPT",
    "WORKOUT_ADAPTATION_PROMPT",
    "EXERCISE_SUBSTITUTION_PROMPT",
    "MEAL_ESTIMATION_PROMPT",
    "PROGRESS_SUMMARY_PROMPT",
]
